import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

const ExportToExcel = () => {
  const RunExcelJSExport = () => {
    let data = [
      {
        'salesman-name': "Jim Smith",
        sales: 12345,
        uri: "https://www.google.com",
        'met target': true,
        status: "Employee",
        dob: new Date(Date.UTC(1950, 0, 1, 0, 0, 0)),
        level: 1.1,
        comments:
          "This is a <b>longish</b> string of text that is intended to show wrapping. The width of the column is set to 30 so the text can&apos;t fit. It also includes some HTML that will be <i>removed</i> and HTML character encodings that will be <i>replaced</i> before export&#33;&#33;"
      },
      {
        'salesman-name': "Mark Thompson",
        sales: 1200,
        'met target': false,
        status: "Employee",
        dob: new Date(Date.UTC(1961, 11, 24, 0, 0, 0)),
        level: 1.3,
        comments: ''
      }
    ];


    let wb = new ExcelJS.Workbook();
    let workbookName = "Sample Workbook Generated by ExcelJS.xlsx";
    let worksheetName = "Demo Worksheet";
    let worksheetName2 = "2nd Demo Worksheet";
    let ws = wb.addWorksheet(worksheetName,
      {
        properties: {
          tabColor: { argb: 'FFFF0000' }
        }
      }
    );
    let ws2 = wb.addWorksheet(worksheetName2);


    ws.columns = [
      {
        key: "salesman-name",
        header: "Salesman-Name",
        width: 20
      },
      {
        key: "sales",
        header: "Sales",
        width: 15,
        style: { numFmt: '"£"#,##0.00;[Red]-"£"#,##0.00' }
      },
      {
        key: "uri",
        header: "URI",
        width: 30,
        outlineLevel: 1,
        hidden: false
      },
      {
        key: "met target",
        header: "Met Target?",
        width: 12,
        style: {
          alignment: { horizontal: "center" },
          font: { color: { argb: "008000" } }
        }
      },
      {
        key: "status",
        header: "Status"
      },
      {
        key: "dob",
        header: "Date of Birth",
        width: 12,
        style: { numFmt: "dd/mm/yyyy" }
      },
      {
        key: "level",
        header: "Level",
        width: 5,
        style: { numFmt: "0.0" }
      },
      {
        key: "comments",
        header: "Comments",
        width: 30,
        style: { alignment: { wrapText: true }, numFmt: '@' },
        outlineLevel: 1,
        hidden: false
      },
      {
        key: "dob_linked",
        header: "Date of Birth (Linked and Formatted)",
        width: 35,
        style: { numFmt: "dddd, MMMM dd, yyyy" },
        outlineLevel: 2,
        hidden: false
      },

    ];

    ws.getRow(1).font = { bold: true };
    ws.getCell("B1").alignment = { horizontal: "right" };
    ws.getCell('F1').alignment = { textRotation: 90 };

    ws.addRows(data);

    ws.getCell("C2").value = {
      text: "www.google.com",
      hyperlink: "http://www.google.com",
      tooltip: "Click to go to google.com"
    };
    ws.getCell("C2").font = {
      color: { argb: "0000FF" },
      underline: true
    };

    let totCell = "B" + (data.length + 2);
    let totFormula = "SUM(B2:B" + (data.length + 1) + ")";
    ws.getCell(totCell).value = { formula: totFormula };
    ws.getCell(totCell).border = {
      top: { style: "thin" },
      bottom: { style: "double" }
    };

    wb.xlsx.writeBuffer()
      .then(function (buffer) {
        saveAs(
          new Blob([buffer], { type: "application/octet-stream" }),
          workbookName
        );
      });
  }

  return (
    <button onClick={() => RunExcelJSExport()}>Download Excel</button>
  );
};

export default ExportToExcel;